version: '3'
services:

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - aa-network
    restart: unless-stopped
    command: --interval 30 --cleanup --label-enable

  traefik:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN}"
      - "traefik.local.frontend.entryPoints=http"
      - "traefik.port=8888"
      - "traefik.backend=traefik"
      - "traefik.docker.network=aa-network"
    image: library/traefik:1.7.16
    ports:
      - 80:80
      - 443:443
      - 8888:8888
      - 4545:8080
    expose:
      - 8888
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/traefik/traefik.toml:/traefik.toml
      - ./conf/docker/traefik/acme.json:/acme.json
    container_name: traefik
    restart: unless-stopped
    command: --docker --insecureSkipVerify=true

  traefik-cert-extractor:
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    image: danielhuisman/traefik-certificate-extractor
    container_name: traefik-cert-extractor
    volumes:
      - ./conf/traefik:/app/data
      - ./conf/traefik/certs:/app/certs
    networks:
      - aa-network
    restart: unless-stopped


  nginx:
    image: nginx:1.15.5
    container_name: aa-nginx
    labels:
      - "traefik.frontend.rule=Host:${SUB_DOMAIN}.${DOMAIN}"
      - "traefik.docker.network=aa-network"
      - "traefik.port=80"
    volumes:
      - ./conf/local.conf:/etc/nginx/conf.d/default.conf
      - static-volume:/var/www/myauth/static
    depends_on:
      - allianceauth
    networks:
      - aa-network

  redis:
    image: redis:3
    container_name: aa-redis
    command: redis-server
    restart: always
    volumes:
      - "redis-data:/data"
    networks:
      - aa-network
    expose:
      - "6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  allianceauth:
    build: .
    container_name: aa-auth
    restart: always
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && /usr/bin/supervisord"
    ports:
      - 5555:5555
    volumes:
      - ./conf/local.py:/home/allianceserver/myauth/myauth/settings/local.py
      - ./templates:/home/allianceserver//myauth/myauth/templates/
      - static-volume:/var/www/myauth/static
    depends_on:
     - redis
    networks:
      - aa-network


networks:
  aa-network:

volumes:
    redis-data:
    static-volume:
